# An example of ClusterConfig object with custom VPC IPv4 CIDR,
# and auto-allocated IPv6 CIDRs for all subnets; also without
# and  two nodegroups:
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod
  region: us-west-1
  version: "1.27"


vpc:
  cidr: 10.50.0.0/16
  autoAllocateIPv6: true
  clusterEndpoints:
    publicAccess: true
    privateAccess: true


managedNodeGroups:
- name: general
  instanceType: t3.small
  instanceName: argo-node
  desiredCapacity: 3
  labels: {role: general}
  volumeSize: 70
  privateNetworking: true

